# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Generate lock file
        run: |
          poetry lock
        # This creates or updates poetry.lock based on your pyproject.toml.

      - name: Install dependencies
        run: |
          poetry install --no-root
        # Installs using the newly generated poetry.lock.

      # - name: Run tests
      #   run: |
      #     poetry run pytest

      - name: Build release distributions
        run: |
          poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists-${{ matrix.python-version }}
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    strategy:
      matrix:
        python-version: ["3.12"]
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists-${{ matrix.python-version }}
