name: Test Python Publish

on:
  push:
    branches: [main]
    
permissions:
  contents: read
  
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Fake build
        run: |
          mkdir dist
          echo "sample" > dist/file.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/




  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
      - name: Publish
        run: echo "Publish step here..."





        
